# Generated by Django 3.1 on 2021-10-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseorder',
            name='total_paid',
        ),
        migrations.RemoveField(
            model_name='baseorder',
            name='total_price',
        ),
    ]
