# Generated by Django 3.1 on 2022-03-03 10:24

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0002_auto_20220303_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='status',
            field=django_fsm.FSMField(choices=[('created', 'CREATED'), ('payed_full', 'PAYED_FULL'), ('payed_partial', 'PAYED_PARTIAL'), ('cancel', 'CANCELED'), ('refunded', 'REFUNDED')], default='created', max_length=50),
        ),
        migrations.AddField(
            model_name='baseorderitem',
            name='status',
            field=django_fsm.FSMField(choices=[('created', 'CREATED'), ('payed_full', 'PAYED_FULL'), ('payed_partial', 'PAYED_PARTIAL'), ('cancel', 'CANCELED'), ('refunded', 'REFUNDED')], default='created', max_length=50),
        ),
    ]
