# Generated by Django 3.1 on 2021-10-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0002_auto_20211019_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='payed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='baseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Полная стоимость'),
        ),
    ]
