# Generated by Django 3.1 on 2022-03-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0003_auto_20220303_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudpaymentinvoice',
            name='price',
        ),
    ]
