# Generated by Django 3.1 on 2021-10-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0003_auto_20211019_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseorderitem',
            name='price',
        ),
    ]
