# Generated by Django 3.1 on 2021-10-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0004_remove_baseorderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
