# Generated by Django 3.1 on 2021-10-24 18:43

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('garpix_order', '0005_baseorderitem_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('status', django_fsm.FSMField(choices=[('created', 'CREATED'), ('pending', 'PENDING'), ('waiting_for_capture', 'WAITING FOR CAPTURE'), ('succeeded', 'SUCCEEDED'), ('cancel', 'CANCELED'), ('faild', 'FAILED'), ('refunded', 'REFUNDED'), ('timeout', 'TIMEOUT'), ('closed', 'CLOSED')], default='created', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Provider transaction id')),
                ('client_data', models.JSONField(blank=True, null=True, verbose_name='Client payment process data')),
                ('provider_data', models.JSONField(blank=True, null=True, verbose_name='Provider payment process data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='garpix_order.baseorder', verbose_name='Заказ')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_garpix_order.baseinvoice_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
