# Generated by Django 3.1 on 2021-11-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0001_squashed_0008_auto_20211105_1533'),
        ('example', '0002_order_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('baseinvoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_order.baseinvoice')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
            bases=('garpix_order.baseinvoice',),
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Ордер', 'verbose_name_plural': 'Ордера'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
