# Generated by Django 3.1 on 2021-11-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20211104_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
