# Generated by Django 3.1 on 2024-05-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0003_auto_20230721_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='SberPayment',
            fields=[
                ('basepayment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_order.basepayment')),
                ('external_payment_id', models.CharField(default='', max_length=255, verbose_name='Внешний идентификатор платежа')),
                ('payment_link', models.CharField(default='', max_length=255, verbose_name='Ссылка на оплату')),
            ],
            options={
                'verbose_name': 'Платеж в Сбере',
                'verbose_name_plural': 'Платежи в Сбере',
                'abstract': False,
            },
            bases=('garpix_order.basepayment',),
        ),
        migrations.AlterField(
            model_name='baseorder',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garpix_order.recurring', verbose_name='Рекуррент'),
        ),
    ]
