# Generated by Django 3.1 on 2024-08-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0004_auto_20240506_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseorder',
            options={'ordering': ('-created_at',), 'verbose_name': 'Базовый заказ', 'verbose_name_plural': 'Базовые заказы'},
        ),
        migrations.AlterModelOptions(
            name='baseorderitem',
            options={'verbose_name': 'Объект заказа', 'verbose_name_plural': 'Объекты заказа'},
        ),
        migrations.AlterModelOptions(
            name='basepayment',
            options={'verbose_name': 'Базовый платеж', 'verbose_name_plural': 'Базовые платежи'},
        ),
    ]
